spring.application.name=APIGateWay

server.port=3000

eureka.client.serviceurl.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.discover.locator.enabled=false
spring.cloud.netflix.eureka.discovery.enabled=true

#Static routes
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTHSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://USERSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/user/**

spring.cloud.gateway.routes[4].id=problem-service
spring.cloud.gateway.routes[4].uri=lb://PROBLEMSERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/problem/**

spring.cloud.gateway.routes[2].id=submission-service
spring.cloud.gateway.routes[2].uri=lb://SUBMISSIONSERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/submission/**

spring.cloud.gateway.routes[3].id=executor-service
spring.cloud.gateway.routes[3].uri=lb://EXECUTORSERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/executor/**

#debugging logs
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.cloud.loadbalancer=TRACE
logging.level.org.springframework.cloud.netflix.eureka=DEBUG

management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=unrestricted