spring.application.name=APIGateWay

server.port=3000

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.server.webflux.discovery.locator.enabled=false

# Auth Service
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AuthService
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# User Service
spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://UserService
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/user/**

# Submission Service
spring.cloud.gateway.server.webflux.routes[2].id=submission-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://SubmissionService
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/submissions/**

# Executor Service
spring.cloud.gateway.server.webflux.routes[3].id=executor-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://ExecutorService
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/execute/**

# Problem Service
spring.cloud.gateway.server.webflux.routes[4].id=problem-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://ProblemService
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/problems/**

logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.cloud.loadbalancer=TRACE
logging.level.org.springframework.cloud.netflix.eureka=DEBUG

management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=unrestricted