spring.application.name=AuthService

server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

## Mail Properties ###
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=2022pecit375pani@gmail.com
spring.mail.password=aqdp ffpk wbyq qwdo

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# MYsql properties

spring.datasource.url=jdbc:mysql://localhost:3306/auth_user
spring.datasource.username=root
spring.datasource.password=Madh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# jwt authentication
jwt.secret=dyJG3WWem8MsbxmwkXugyqJnUbDNpgdi4TerxHw1m04=
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000